version: '3'

services:
  db:
    container_name: ${PROJECT_NAME}_db
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - network
  backend:
    image: ${PROJECT_NAME}_backend
    container_name: ${PROJECT_NAME}_backend
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/api
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - network

volumes:
  postgres_data:

networks:
  network:
