name: Acceptance
on: push
jobs:
  check-lint:
    name: Check Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python environment
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Install requirements
      run: pip install -r requirements.dev.txt
    - name: Black
      run: black --check .
    - name: Ruff
      run: ruff check .
    - name: Mypy
      run: mypy .
